[package]
name = "fpapp"
version = "4.0.0"
description = "fp app"
authors = ["Phil Spindler"]
license = ""
repository = ""
default-run = "fpapp"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
flexi_logger = "0.24.2"
image = "0.24.5"
log = "0.4.17"
plotters = "0.3.4"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-shell = "2.0.0-beta"
tauri-plugin-dialog = "2.0.0-beta.10"
tauri-plugin-fs = "2.0.0-beta.10"

toml = "0.5.11"

accounts = { path = "./src/accounts" }

