// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * description used to populate account dropdown for contribution type selection
 */
export type ContributionOptions = "fixed" | "percent_of_income" | "fixed_with_inflation";
