// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PercentInput } from "./PercentInput";

/**
 * Employer matching for retirement accounts
 */
export type EmployerMatch = { 
/**
 * Percentage that the employer will match (such as 50%)
 */
amount: PercentInput, 
/**
 * Limit of employer's match (such as up to the first 6% that the employee saves)
 */
limit: PercentInput, };
