// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpenseOptions } from "./ExpenseOptions";
import type { Table } from "./Table";
import type { YearInput } from "./YearInput";

/**
 * Account type to represent generic expense
 */
export type Expense<T> = { 
/**
 * String describing this account
 */
name: string, 
/**
 * Table of account expense for each year
 */
table: Table<T>, 
/**
 * Calendar year when then expense of this account started to have impact
 */
startOut: YearInput, 
/**
 * Calendar year when then expense of this account no longer has impact
 */
endOut: YearInput, 
/**
 * Determines how to interpret expense_value
 */
expenseType: ExpenseOptions, 
/**
 * Yearly cost of the expense [in today's dollars]
 */
expenseValue: number, 
/**
 * This expense account is for healthcare costs.  If so it will pull first from HSA accounts.
 */
isHealthcare: boolean, 
/**
 * When false, this expense is not scaled by the retirement cost-of-living factor.
 * Use this for fixed obligations (loan payments, insurance premiums) that do not
 * change with retirement lifestyle. Defaults to true.
 */
scalesWithCol: boolean, 
/**
 * Link this account to an income source
 */
hsaLink: string | null, 
/**
 * General information to store with this account
 */
notes: string | null, };
