// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PercentInput } from "./PercentInput";
import type { Table } from "./Table";
import type { YearInput } from "./YearInput";

/**
 * Account to represent sources of income
 */
export type Income<T> = { 
/**
 * String describing this account
 */
name: string, 
/**
 * Table of account income
 */
table: Table<T>, 
/**
 * Base pay (with bonuses) [in today's dollars]
 */
base: number, 
/**
 * Calendar year when money starts being earned by this account
 */
startIn: YearInput, 
/**
 * Calendar year when money stops being earned by this account
 */
endIn: YearInput, 
/**
 * Yearly increase in income as a percent
 */
raise: PercentInput, 
/**
 * General information to store with this account
 */
notes: string | null, };
