// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentOptions } from "./PaymentOptions";
import type { PercentInput } from "./PercentInput";
import type { Table } from "./Table";
import type { YearInput } from "./YearInput";

/**
 * Generic loan
 */
export type Loan<T> = { 
/**
 * String describing this account
 */
name: string, 
/**
 * Table of outstanding loan balance
 */
table: Table<T>, 
/**
 * Calendar year when payments to this account start
 */
startOut: YearInput, 
/**
 * Calendar year when payments to this account stop
 */
endOut: YearInput, 
/**
 * Determines how to interpret payment_value
 */
paymentType: PaymentOptions, 
/**
 * How much money should be payed each year (either as a percentage or a fixed dollar amount) [in today's dollars]
 */
paymentValue: number, 
/**
 * Interest rate on borrowed money. This is an APR this is then compounded based on the compound time setting.  Used for LOAN and MORTGAGE account types.
 */
rate: PercentInput, 
/**
 * General information to store with this account
 */
notes: string | null, };
