// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaymentOptions } from "./PaymentOptions";
import type { PercentInput } from "./PercentInput";
import type { Table } from "./Table";
import type { YearInput } from "./YearInput";

/**
 * Loan type specifically tailored for mortgages
 */
export type Mortgage<T> = { 
/**
 * String describing this account
 */
name: string, 
/**
 * Table of outstanding mortgage balance
 */
table: Table<T>, 
/**
 * Calendar year when payments to this account start
 */
startOut: YearInput, 
/**
 * Calendar year when payments to this account stop
 */
endOut: YearInput, 
/**
 * Determines how to interpret payment_value
 */
paymentType: PaymentOptions, 
/**
 * How much money should be payed each year (either as a percentage or a fixed dollar amount) [in today's dollars]
 */
paymentValue: number, 
/**
 * Interest rate on borrowed money. This is an APR this is then compounded based on the compound time setting.  Used for LOAN and MORTGAGE account types.
 */
rate: PercentInput, 
/**
 * Number of times per year that interest is compounded. (1=yearly, 12=monthly)
 */
compoundTime: number, 
/**
 * Mortgage insurance payment expressed as a yearly fixed number [in today's dollars]
 */
mortgageInsurance: number, 
/**
 * Loan to Value amount when mortgage insurance is no longer pulled from payment.  Since monthly payment does not change over time, after the insurance is done there is more money going to the principal each payment
 */
ltvLimit: number, 
/**
 * Amount of money going into escrow every year to pay for property tax.  This number is currently assumed to be constant (ie property taxes do not increase) [in today's dollars]
 */
escrowValue: number, 
/**
 * Current value of the home.  This is used to compute loan to value [in today's dollars]
 */
homeValue: number, 
/**
 * General information to store with this account
 */
notes: string | null, };
