// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * used to populate account dropdown for payment type selection
 */
export type PaymentOptions = "fixed" | "fixed_with_inflation";
