// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for strings on percent inputs
 *
 * These are smart values that correlate to values previously defined in the application.
 * When selected by the user the correlating value will be returned.  For example,
 * the base inflation rate is defined in the general application settings but can be
 * selected as the value for any field that is a percent such that if you change the base
 * inflation setting then that account's percent value (such as increase in an expense) will
 * change to reflect the newly set value.
 */
export type PercentSuggestions = "inflationBase";
