// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionOptions } from "./ContributionOptions";
import type { EmployerMatch } from "./EmployerMatch";
import type { PercentInput } from "./PercentInput";
import type { Table } from "./Table";
import type { TaxStatus } from "./TaxStatus";
import type { WithdrawalOptions } from "./WithdrawalOptions";
import type { YearInput } from "./YearInput";

/**
 * Generic retirement account type applicable for 401K, Roth IRA, IRA, etc.
 */
export type Retirement<T> = { 
/**
 * String describing this account
 */
name: string, 
/**
 * Table of account balance
 */
table: Table<T>, 
/**
 * Table of contributions to this account
 */
contributions: Table<T> | null, 
/**
 * Table of account earnings
 */
earnings: Table<T> | null, 
/**
 * Table of withdrawals from this account
 */
withdrawals: Table<T> | null, 
/**
 * Table of employer contributions to this account [in today's dollars]
 */
employerContributions: Table<T> | null, 
/**
 * Calendar year when money starts being added to this account
 */
startIn: YearInput, 
/**
 * Calendar year when money is no longer added to this account (this value is inclusive and is often yearRetire-1)
 */
endIn: YearInput, 
/**
 * Calendar year when money starts being withdrawn from this account
 */
startOut: YearInput, 
/**
 * Calendar year when money stops being withdrawn from this account
 */
endOut: YearInput, 
/**
 * Amount put into this account every year.  Numbers less than 100 are assumed to be a percentage. [in today's dollars]
 */
contributionValue: number, 
/**
 * Determines how to interpret the value in yearly_contribution
 */
contributionType: ContributionOptions, 
/**
 * Percent interest earned each year
 */
yearlyReturn: PercentInput, 
/**
 * Determines how to interpret the value in withdrawal_value
 */
withdrawalType: WithdrawalOptions, 
/**
 * How much money should be take out per year (either as a percentage or a fixed dollar amount) [in today's dollars]
 */
withdrawalValue: number, 
/**
 * How cashflow in this account is treated for tax purposes
 */
taxStatus: TaxStatus, 
/**
 * Link to income account used with employer contributions and some contribution types
 */
incomeLink: string | null, 
/**
 * Percent of your contribution that your employer matches
 */
matching: EmployerMatch | null, 
/**
 * General information to store with this account
 */
notes: string | null, };
