// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SsaSettings } from "./SsaSettings";

/**
 * Analysis user settings
 */
export type Settings = { 
/**
 * Age you plan to retire at
 */
ageRetire: number, 
/**
 * How long you plan to live
 */
ageDie: number, 
/**
 * Year you were born in
 */
yearBorn: number, 
/**
 * Year to start the simulation
 */
yearStart: number, 
/**
 * Base rate of inflation (percent)
 */
inflationBase: number, 
/**
 * Tax rate for your income bracket
 */
taxIncome: number, 
/**
 * Tax rate for capital gains
 */
taxCapitalGains: number, 
/**
 * Fraction of current spending when retired (such as in retirement you will spend 80% of what you spend now)
 */
retirementCostOfLiving: number, 
/**
 * Social Security settings
 */
ssa: SsaSettings, };
