// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic span (something that has a min and max value)
 */
export type Span<T> = { 
/**
 * Minimum value
 */
low: T, 
/**
 * Maximum value
 */
high: T, };
