// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YearInput } from "./YearInput";

/**
 * Social Security Account
 */
export type Ssa = { 
/**
 * String describing this account
 */
name: string, 
/**
 * Base income from social security
 */
base: number, 
/**
 * Calendar year when SSA benefits start
 */
startIn: YearInput, 
/**
 * Calendar year when SSA benefits end
 */
endIn: YearInput, 
/**
 * General information to store with this account
 */
notes: string | null, };
