// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * Social Security span settings
 */
export type SsaSettings = { 
/**
 * SSA breakpoints to interpolate between
 */
breakpoints: Span<number>, 
/**
 * taxable_income_percentage
 */
taxableIncomePercentage: Span<number>, };
