// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Table is a map keyed by year that holds account values/amounts.
 *
 * Tables are stored as keyed on string but must be converted to
 * be keyed on a u32 year prior to use for analysis.
 */
export type Table<T> = { [key in T]: number };
