// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * used to populate account dropdown for tax status selection
 */
export type TaxStatus = "contribute_taxed_earnings_untaxed_when_used" | "contribute_taxed_earnings_taxed" | "contribute_pretax_taxed_when_used" | "contribute_pretax_untaxed_when_used";
