// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings";

/**
 * Represents the user data file
 */
export type UserData<T> = { 
/**
 * The system level configuration
 */
settings: Settings, 
/**
 * The metrics that data will be generated for
 */
accounts: { [key in string]: T }, };
