// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * used to populate account dropdown for withdrawal type selection
 */
export type WithdrawalOptions = "fixed" | "fixed_with_inflation" | "end_at_zero" | "col_frac_of_savings" | "other";
