// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for strings on year inputs
 */
export type YearEvalType = "startIn" | "endIn" | "startOut" | "endOut";
