// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YearComputation } from "./YearComputation";
import type { YearSuggestion } from "./YearSuggestion";

/**
 * These values can be input as constants or as computed values (strings)
 */
export type YearInput = YearComputation | YearSuggestion | number;
