// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YearSuggestion } from "./YearSuggestion";

/**
 * Struct to hold info about computed year values
 */
export type YearComputation = { base: YearSuggestion, delta: number, };
